services:

  incer-paygate:
    container_name: incer-paygate
    image: incer-paygate:0.0.1-SNAPSHOT
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/paymentDB
    ports:
      - "8080:8080"
    networks:
      -   incerpay_network

  incer-payment:
    container_name: incer-payment
    image: incer-payment:0.0.1-SNAPSHOT
    ports:
      - "1111:8080"
    networks:
      -   incerpay_network

  incer-celler:
    container_name: incer-celler
    image: incer-celler:0.0.1-SNAPSHOT
    ports:
      - "2222:8080"
    networks:
      - incerpay_network

  incer-member:
    container_name: incer-member
    image: incer-member:0.0.1-SNAPSHOT
    ports:
      - "3333:8080"
    networks:
      -   incerpay_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - incerpay_network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: admin
      MYSQL_PASSWORD: incerpay1234!!
    networks:
      - incerpay_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  incerpay_network:
    name: incerpay_network
    driver: bridge