services:
  incer-payment:
    container_name: incer-payment
    image: incer-payment:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      -   incerpay_network

  incer-member:
    container_name: incer-member
    image: incer-member:0.0.1-SNAPSHOT
    ports:
      - "8081:8080"
    networks:
      -   incerpay_network

  incer-paygate:
    container_name: incer-paygate
    image: incer-paygate:0.0.1-SNAPSHOT
    ports:
      - "8082:8080"
    networks:
      -   incerpay_network

  incer-celler:
    container_name: incer-celler
    image: incer-celler:0.0.1-SNAPSHOT
    ports:
      - "8083:8080"
    networks:
      -   incerpay_network

networks:
  incerpay_network:
    name: incerpay_network
    driver: bridge